title: JJukE's Portfolio
name: 박상준
email: psj9156@gmail.com
description: >-
  Mechanical Engineer & A.I developer


baseurl: ""
url: "https://jjukeportfolio.github.io"


# profile 이미지
profile_image: images/me.JPG


# SNS 아이디
instagram_id: jjuke_sangjune


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_3.JPG
  title: JJukE's <br>Portfolio</br>
  position: absolute
  transform: translate( -50%, -50%)
  left: -260px
  bottom: 680px


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/img_bg_4.jpeg
  title: I am<br>AI<br>Developer
  subtitle: >- 
    꾸준히 성장하고<br>
    끊임없이 노력하는<br>
    초보 개발자 쭈기입니다.
  position: absolute
  transform: translate( -50%, -50%)
  left: 600px
  bottom: 0px


# About
about_meta: About Me
about_header: >- 
  "끊임없이 배우는 대학생"
about_introduce: >-
  "안녕하세요. 인공지능 및 자율주행 분야 전문가를 꿈꾸는 개발자, 박상준입니다."
about_content: >-
  어렸을 때부터 활발했고 스스로 다양한 도전을 해왔습니다.
  욕심이 많아, 일단 시작한 일은 끈기 있게 목표한 바를 이루고 인정받기 위해 열심히 달렸습니다. <br>
  수학과 과학에 관심이 많아 과학중점고등학교에 진학하였으며, 기계시스템디자인공학과로 진학하였습니다.
  못하지는 않았지만 특별히 잘하거나 흥미가 많지는 않았던 1학년 학부를 마친 후,
  2016년도에 22사단 최전방에서 군 복무를 하였습니다. <br>
  진로에 관한 많은 생각을 뒤로한 채 1년의 휴학기간동안 취미인 보컬과 힙합에도 푹 빠져보고,
  자동차 부품연구소 알바, 현대자동차 계약직에서 현장 일 등을 해보며 돈을 벌어 보았습니다. <br>
  <br>
  복학 후 코딩에 흥미를 느껴 내가 원하는 기능을 하는 어플을 개발해보자는 취지로
  스스로 앱 개발을 배워보았고, 여러 프로그래밍 언어를 익혔습니다.
  <strong>또한 4차 산업혁명이 큰 화두로 떠오르고 있는 현실에서 관련 산업의 기업들에 관심이 갔고,
  인공지능이라는 신기술에 매료되어 2020년 2학기부터 ICT인공지능 연계 복수전공을 진행했습니다.</strong>
  또한 2019년부터 시작한 학부연구생으로서 연구 진행 과정을 직접 경험하고, 논문을 작성해 보기도 하였습니다.
  친구들이 모두 취업 시장으로 떠나가는 동안, 힘들고 외롭지만 꾸준히, 후회 없이 저만의 길을 걸어가고 있습니다.
  평생 배움과 연구를 놓지 않으며 스스로를 계발해 나가는 이 분야의 최고가 되고 싶습니다.

about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: Data Mining
- icon: icon-monitor
  name: ML, DL, RL
- icon: icon-phone3
  name: Mechanical ENG
- icon: icon-code
  name: Python, C++
about_box_content: 배움에는 끝이 없다는 말을 새기며 <br>매일 자신을 계발하는 <strong>'꾸준히 갱신하는' 전문가가 되겠습니다. </strong>

about_box_content_color: rgb(255, 255, 255)

about_box_button:
  link: https://drive.google.com/file/d/1HSmCqSIOFj0hCrP_l0h43i_YNWQB8t1c/view?usp=sharing
  name: CV


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 제 역량은 다음과 같습니다.
tech_content:
tech_list: # 형식에 맞추어 항목 추가
- name: >-
    Python <br><br>
  color: color-1
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: >-
    파이썬 기초, 데이터 분석, 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 파이썬으로 공부하였습니다.
    또한 여러 프로젝트를 통해 Tensorflow를 사용하여 인공지능을 구현하였습니다. <br><br>

- name: >-
    머신러닝, 딥러닝, 강화학습, 데이터 분석 <br><br>
  color: color-2
  animation: fadeInRight
  percent: 50
  mark: 50
  content: >-
    공부하면 공부할수록 해당 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다.
    이론부터 차근차근 다시 배우겠다는 마음으로 공부하고 있습니다. <br><br><br><br>

- name: >-
    Mechanical Engineering <br><br>
  color: color-3
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: >-
    전공 과목으로 4대역학을 수강하고 해당 내용들을 나중에 다시 복기할 수 있도록 정리해 두었습니다.
    여러 영역에서 기계공학적 지식과 인공지능 역량을 결합하여 좋은 성과를 낼 수 있을 것입니다. <br><br>

- name: >-
    Github <br><br>
  color: color-4
  animation: fadeInRight
  percent: 20
  mark: 20
  content: >-
    일부 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다.
    또한 github서버를 활용하여 포트폴리오 사이트를 관리합니다. <br><br>

tech_desc: 앞으로 추가적인 연구를 위해 <strong>PyTorch, docker, Scala(Spark), 자율주행(인지, 판단, 제어)</strong>등을 계속해서 공부할 생각입니다. 


# Project
project_meta: My Work
project_header: PROJECTS
project_introduce:
  제가 진행했던 프로젝트들을 소개합니다.
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_my_name: 수업에서 진행한 텀프로젝트

project_my: # 형식에 맞추어 항목 추가
- background_url: images/term_project1.jpg
  animation: fadeInLeft
  name: 스마트폰 센서를 이용한 오토바이 최적 경로 추적(2019.12)
  description: >-
    2학년 2학기 '공학프로그래밍'이라는 과목의 텀 프로젝트이다. 총 4명의 팀원으로 진행하였다.
    기존의 여러 교통 정보 뿐만 아니라 센서를 통해 경로 상의 노면 상태를 고려하여 경로를 추천해주는 프로그램을 MATLAB을 통해 개발하였다.
    MATLAB이라는 프로그램 하나로도 센서 데이터를 읽어오고 threshold를 지정하여 GUI를 통해 프로그램을 만들 수 있다는 사실을 알게 되었고,
    어플리케이션에 간단한 하나의 기능을 추가하는 것이 얼마나 힘든 일인지를 깨닫게 되었다.
    또한 이 term project를 통해 코딩에 관심이 생겼다.
  detail_url: #
  readmore_url: #

- background_url: images/term_project2.jpg
  animation: fadeInLeft
  name: Circle Breeding Game(2020.06)
  description: >-
    3학년 1학기 '마이크로컨트롤러'라는 과목의 텀 프로젝트이다. 총 2명의 팀원으로 진행하였다.
    브레드보드에 가속도계 등의 회로를 구성하여 컨트롤러를 만들고, 아두이노를 사용하여 센서 값을 측정한 후,
    Serial 단방향 통신을 통해 값을 PC로 송신하고 C# 프로그래밍을 통해 자신보다 큰 원을 피하고 작은 원을 잡아먹으며 원의 크기를 키우는 게임을 개발하였다.
    이 프로젝트를 통해 기계공학적, 전기공학적 지식과 프로그래밍 능력을 모두 함양한다면 유용한 장치를 개발할 수 있을 것이라는 자신감과 꿈을 갖게 되었다.
  detail_url: #
  readmore_url: https://youtu.be/pNFx73Wn4Fs

- background_url: images/term_project3.jpg
  animation: fadeInLeft
  name: 가위바위보 로봇(2020.12)
  description: >-
    3학년 2학기 '로봇공학'이라는 과목의 텀 프로젝트이다.
    개인 프로젝트로 진행되었으며, 손 모양의 로봇의 모습과 움직임을 프로그래밍을 통해 살펴보는 프로젝트였다. 
    특히, 손가락 마디의 움직임을 통해 가위바위보 형상을 구현하였다.
    원하는 로봇을 직접 만들지 않고도 OpenGL API, C++언어를 통해 움직임을 시뮬레이션 해볼 수 있다는 사실을 깨다았고,
    하나의 언어를 통달하는 것이 중요한 것이 아니라, 기능을 구현하기 위해 어떻게 필요한 지식을 검색하고 내 어플리케이션에 적용할지가 더 중요하다는 사실을 깨달았다.
  detail_url: #
  readmore_url: #

- background_url: images/term_project4.jpg
  animation: fadeInLeft
  name: Self-balancing Bike(2020.12)
  description: >-
    3학년 2학기 '자동화시스템'이라는 과목의 텀 프로젝트이다. 
    4명의 팀원이 기계공학적 지식과 프로그래밍 지식을 통해 설계와 제어를 맡아 간단한 작품을 만들어보는 실습 과목이다.
    오토바이에 모멘트 평형을 일으키는 Reaction Wheel을 장착하여 PID 제어를 통해 밸런스를 유지하는 오토바이를 개발하려 하였다.
    하지만 random하게 수많은 시행착오를 겪어야 PID 제어 gain 값을 구할 수 있었는데, 시간적 여유가 부족하여 값을 얻는 데 실패하였고,
    차체의 기울기에 따라 모터에 pwm 값을 가하여 토크를 주는 bang-bang control을 구현하였지만 현실에서 안정적인 구현이 불가능했다.
    하지만 여러 시도를 해보면서 많은 이론과 시행착오를 겪으며 성장하였고, 프로젝트 진행에는 사전 조사가 매우 중요하다는 사실을 깨달았다.
  detail_url: #
  readmore_url: https://youtu.be/GTKjT0mgtsQ

- background_url: images/term_project5.png
  animation: fadeInLeft
  name: Gesture Recognition and Gesture Based UI Prototype(2021.06)
  description: >-
    4학년 1학기 '딥러닝' 과목의 텀 프로젝트이다. 
    3명의 팀원이 진행하였으며, 디바이스와 인간의 상호작용을 위해 웹캠을 통해 얻은 사람의 손 모양을 딥러닝을 통해 컴퓨터가 인식하도록 하는 프로젝트이다.
    Kaggle data를 사용하려 하였지만, 성능이 좋지 않아서 웹캠 캡쳐 기능을 통해 직접 데이터를 만들어 dropout, data augmentation 등의 기법을 적용하여 학습시켰다.
    96퍼센트의 높은 정확도를 보이는 모델을 얻었으며, JavaScript 언어로 구현된 실시간으로 손모양을 판별하는 프로그램을 통해 입증했다.
    교수님과 같이 수업 들은 다른 학생들에게 극찬을 받으며 만점을 받은 프로젝트인 만큼, 인공지능에 대한 흥미와 적성을 더 깨우쳐준 프로젝트였다.
  detail_url: https://github.com/lee-euijin/AppleFarm/blob/main/Master/Deep_Learning_Project__Team_1_final.ipynb
  readmore_url:

- background_url: images/term_project6.jpg
  animation: fadeInLeft
  name: 뉴스 기사 감성 분석을 사용한 중, 장기적 주가 예측 프로그램(2021.06)
  description: >-
    4학년 1학기 '데이터마이닝' 과목의 텀 프로젝트이다. 
    3명의 팀원이 진행하였으며, RPA를 통한 뉴스 기사의 title, date, content를 crawling하여 데이터를 직접 생성한 후, 감성 분석을 통해 긍정/부정을 판별한다.
    또한 재무재표의 다른 data와 함께 Regression 기법을 적용하여 중, 장기적인 주가를 예측한다.
    RPA 솔루션을 사용하여 코딩 없이 수많은 뉴스 기사들을 크롤링할 수 있음을 알게 되었고, data를 다루는 Regression 기법과 text mining 기법을 직접 구현해보며 역량을 키울 수 있었다.
  detail_url: https://github.com/JJukE/DataMining
  readmore_url: https://youtu.be/WOaKpZnq704

- background_url: images/term_project7.jpg
  animation: fadeInLeft
  name: 지방소멸의 요인 분석(2021.12)
  description: >-
    4학년 2학기 '비즈니스인텔리전스' 과목의 텀 프로젝트이다. 
    5명의 팀원이 진행하였으며, 제공된 dataset에서 target 값 및 모델을 선정하여 Random Forest 기법을 사용하여 세 번의 분석 과정을 거쳐 지방 소멸에 영향을 주는 요인을 분석한다.
    데이터 분석 및 시각화를 Python이 아닌 RapidMiner와 Tableau를 통해 직관적으로 실행해볼 수 있었다.
  detail_url: #
  readmore_url: #

- background_url: images/term_project8.jpg
  animation: fadeInLeft
  name: 빅데이터를 활용한 스핀들 모터 고장 요인 분석(2021.12)
  description: >-
    4학년 2학기 '빅데이터분석' 과목의 텀 프로젝트이며, 연구실 과제의 일부를 진행하였다.
    2명의 팀원이 진행하였으며, 고속 스핀들 모터에 부착한 가속도, 변위 센서로부터 얻은 6.6억개의 데이터를 전처리하여 고장 패턴을 분석하는 프로젝트를 진행하였다.
    기계공학적 지식, 신호 처리에 관한 지식, 프로그래밍 지식, 데이터 분석 기법에 관한 지식 등 많은 분야의 지식들을 융합하여 의미있는 결과를 얻어내면서,
    나만의 역량을 제대로 발휘해볼 수 있었던 프로젝트였다.
  detail_url: https://github.com/JJukE/BigDataAnalysis
  readmore_url: #

- background_url: images/term_project9.jpg
  animation: fadeInLeft
  name: 마이크로툴 가공용 CNC 공작기계의 공작물 클램핑 툴 개발(2021.12)
  description: >-
    졸업작품 과목인 Capstone Design 프로젝트이다.
    4명의 팀원이 진행하였으며, 크게 'CAE 해석을 통한 기존 벤치마킹 모델 재설계 및 타당성 검증', '기구학 Matrix를 사용한 Precision Program', 'VR Interactive Platform'의 3가지 주제로 나뉜다.
    CAE 정적 해석을 통해 기존 우수 제품의 SteadyRest를 재설계하고, CAE 열적 해석 및 실험을 통해 타당성을 검증하였다.
    또한 기구학 Matrix를 사용하여 Base 부분의 틀어짐이 공구 지지 부분에 얼마나 영향을 주는지 계산하는 프로그램을 만들었다.
    그리고 전반적 모델의 VR Manual 및 시뮬레이션을 Unity를 통해 만들었으며, Precision Program을 C#으로 재구현하여 VR apk에 구현하였다.
  detail_url: #
  readmore_url: https://youtu.be/yZ6Atqf39gQ

project_team_name: 연구실 프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/lab_project1.jpg
  animation: fadeInRight
  name: Spindle Appraisal Project(ing)
  description: 스핀들 역설계, 해석 등의 과정을 거친 후 고속 스핀들의 파손 징후를 분석한다. (빅데이터분석 과목의 텀 프로젝트와 연동)
  detail_url: #
  readmore_url: #

- background_url: images/lab_project2.jpg
  animation: fadeInRight
  name: 스마트팩토리용 실감형 AR 인터렉티브 콘텐츠 플랫폼 개발(ing)
  description: 메타버스 시대에 발맞춰 Capstone Design에서 VR Interactive Platform을 개발하였던 것과 연동하여 스마트팩토리를 위한 플랫폼을 개발한다.
  detail_url: #
  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 매니지먼트
  color: color-1
  icon: icon-bulb
  content: 학부 과정동안 진행한 9개 중 8개의 과목 텀 프로젝트에서 팀장을 맡아 각 팀원들의 능력을 파악하고 업무를 배정하고 관리하였습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
- name: 기타 Tool 활용 능력
  color: color-4
  icon: icon-monitor
  content: NX, Inventor, Solidworks 등의 3D 설계 툴, ANSYS 해석 툴, MATLAB, Arduino와 같은 Tool 사용에 능숙하며, C, Java, Swift, C#, Scala 언어를 다뤄본 경험이 있습니다.
exp_counters:
- name: projects
  count: 11
  speed: 2000
- name: papers
  count: 3
  speed: 2000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: PNP Engineering (Part Time Job)
  date: 2017.12~2018.02
  content: 자동차 샤시 부품 연구를 위한 Setting (공구를 사용한 분해/조립, 센서 부착 등)<br> 현대자동차 남양연구소에서 부품 연구 과정 경험
  color: color-1
  icon: icon-spanner
  animation: fadeInLeft
- name: 현대자동차 (Contract Worker)
  date: 2018.08~2019.02
  content: 현대자동차 울산공장에서 의장, 도장 등의 현장직 일을 맡아 자동차가 완성되어가는 과정을 몸소 경험
  color: color-2
  icon: icon-spanner
  animation: fadeInLeft
- name: Spindle Appraisal Project (연구실 과제)
  date: 2019.10~
  content: Spindle 역설계<br> 센서 신호 FFT 변환<br> 이상 신호 감지를 위한 Clustering (팀 프로젝트와 연동) - 진행중
  color: color-3
  icon: icon-pen2
  animation: fadeInLeft
- name: Realistic AR Interactive Contents for Smart Factory (연구실 산학 협력 과제)
  date: 2020.01~
  content: 실감형 원격 교육, System Engineer와 현장 작업자 간 협업 Contents, Simulation, 정밀도 프로그램을 포함하는 VR Interactive Platform 개발
  color: color-4
  icon: icon-pen2
  animation: fadeInLeft


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: SEOUL NATIONAL UNIVERSITY OF SCIENCE AND TECHNOLOGY
  subtitle: 서울과학기술대학교 기계시스템디자인공학과, ICT인공지능 연계전공 재학중
  date: 2015.03 - 2022.08(예정)
  content: 복수전공으로 졸업 예정
- title: ULSAN JOONGANG HIGH SCHOOL
  subtitle: 울산중앙고등학교
  date: 2012.03 - 2015.02
  content: 과학중점고등학교, 이과


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 매일 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: JJukE's brain
  subtitle: 개인 블로그 (티스토리)
  date: 2021.01
  content: 전문적인 프로그래머들을 보면서 부러웠고, 좌절도 하였지만 포기하지않고 어느 한분야의 최고의 전문가가 되겠다는 마음으로 꾸준히 제가 배우는 내용을 정리하는 블로그를 운영하고 있습니다.
  thumbnail_url: images/blog-1.jpg
  link: https://jjuke-brain.tistory.com/


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: psj9156@gmail.com
  icon: icon-globe-outline
- title: 서울특별시 노원구
  icon: icon-map
- title: GITHUB
  icon: icon-layers2
  url: https://github.com/JJukE
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true